# Generated by Django 5.2.4 on 2026-04-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_author_age_alter_author_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='adult',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
